version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:QvSjl3rE6kn7qByBLFiZffie9xsnTNEx5OOOPRv4VKo=
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: multitranslation
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: multitranslation
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www
    depends_on:
      - app

volumes:
  app-data:
